#Question : 01

You are given two strings s and t. String t is generated by randomly
shuffling string s and then adding one more letter at a random position.
Return the letter that was added to t.

Examples

find_the_difference("abcd", "abcde") ➞ "e"

find_the_difference("", "y") ➞ "y"

find_the_difference("ae", "aea") ➞ "a"

In [5]:
#code
def find_the_difference(str1,str2):
    N=[]
    for i in str1:
        if i not in N:
            N.append(i)
    for i in str2:
        if (i not in N):
            return i
        else:
            N.remove(i)
    return "Same "

In [6]:
find_the_difference("abcd", "abcde")

'e'

In [7]:
find_the_difference("", "y")

'y'

In [8]:
find_the_difference("ae", "aea")

'a'

#Question : 02

Given a function that accepts unlimited arguments, check and count how
many data types are in those arguments. Finally return the total in a list.

List order is:

[int, str, bool, list, tuple, dictionary]

Examples

count_datatypes(1, 45, "Hi", False) ➞ [2, 1, 1, 0, 0, 0]

count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1) ➞ [3, 0, 0, 1, 1, 0]

count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1,
3], {"Brayan": 18}, 25, 23) ➞ [2, 2, 3, 1, 0, 2]

count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6]) ➞ [2,
0, 1, 2, 2, 0]

In [10]:
def count_datatypes(*args):
    integer = 0
    string = 0
    boolean = 0
    list_ = 0
    tuple_ = 0
    dictionary = 0
    other = 0
    for i in args:
        if type(i) == int:
            integer+=1
        elif type(i) == str:
            string +=1
        elif type(i) == bool:
            boolean +=1
        elif type(i) == list:
            list_ +=1
        elif type(i) == tuple:
            tuple_ +=1
        elif type(i) == dict :
             dictionary +=1
        else:
            other+=1
    return [integer,string,boolean,list_,tuple_,dictionary]

In [11]:
count_datatypes(1, 45, "Hi", False)

[2, 1, 1, 0, 0, 0]

In [12]:
count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1)

[3, 0, 0, 1, 1, 0]

In [13]:
count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1,3], {"Brayan": 18}, 25, 23)

[2, 2, 3, 1, 0, 2]

In [15]:
count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6])

[2, 0, 1, 2, 2, 0]

#Question : 03

A Fibonacci string is a precedence of the Fibonacci series. It works with
any two characters of the English alphabet (as opposed to the numbers 0 and
1 in the Fibonacci series) as the initial items and concatenates them together
as it progresses in a similar fashion as the Fibonacci series.

Examples

fib_str(3, ["j", "h"]) ➞ "j, h, hj"

fib_str(5, ["e", "a"]) ➞ "e, a, ae, aea, aeaae"

fib_str(6, ["n", "k"]) ➞ "n, k, kn, knk, knkkn, knkknknk"

In [49]:
#code
def fib_str(num, lst):
    num = num-1
    count = 0
    sum = 0
    f1 , f2 = lst[0],lst[1]
    fiboStr = []
    if num <= 0:
        print("Not a positive number")
    elif num == 1:
        print("Fibonacci series upto ",num+1, ":")        
        return a
    else:
        print("Fibonacci series upto ",num+1, ":")
        while count <= num:   
            fiboStr.append(f1)
            count+=1
            if count > num:
                return ', '.join(fiboStr)
            fth = f2 + f1
            f1,f2 = f2, fth

In [50]:
fib_str(3, ["j", "h"])

Fibonacci series upto  3 :

'j, h, hj'

In [51]:
fib_str(5, ["e","a"])

Fibonacci series upto  5 :

'e, a, ae, aea, aeaae'

In [52]:
fib_str(6, ["n","k"])

Fibonacci series upto  6 :

'n, k, kn, knk, knkkn, knkknknk'

#Question : 04

Given an integer between 0 and 26, make a variable (self.answer). That
variable would be assigned to a string in this format:

"nines:your answer, threes:your answer, ones:your answer"

You need to find out how many ones, threes, and nines it would at least take
for the number of each to add up to the given integer when multiplied by one,
three or nine (depends).

Examples

ones_threes_nines(10) ➞ "nines:1, threes:0, ones:1"

ones_threes_nines(15) ➞ "nines:1, threes:2, ones:0"

ones_threes_nines(22) ➞ "nines:2, threes:1, ones:1"

In [53]:
def ones_threes_nines(answer):
    nines = 0
    threes = 0
    zeros = 0
    
    nines = answer//9
    threes = (answer%9)//3
    ones = (answer%9)%3
    
    return f"nines:{nines} ; threes:{threes} ; ones:{ones} "

In [54]:
print(ones_threes_nines(10))

nines:1 ; threes:0 ; ones:1

In [55]:
ones_threes_nines(15)

'nines:1 ; threes:2 ; ones:0 '

In [56]:
ones_threes_nines(22)

'nines:2 ; threes:1 ; ones:1 '

#Question : 05

The Fibonacci sequence is a classic use case for recursive functions since
the value of the sequence at a given index is dependent on the sum of the
last two values. However, the recursion tree created by solving the Fibonacci
sequence recursively can grow quite fast. Therefore it can be important to
think about the implications of running a function recursively. Depending on
the size of n needed and the capabilities of the system in question you might
want to take a different approach.

Write a non-recursive function that takes an integer n and returns the
Fibonacci sequence's value at index n.

Examples

fib(6) ➞ 8
# 0 + 1 = 1, 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8

fib(1) ➞ 1

fib(2) ➞ 1

In [59]:
def fibo(num):
    if (num<=0):
        return 0
    elif (num==1):
        return 1
    else:
        return fibo(num-1)+fibo(num-2)

In [60]:
fibo(1)

1

In [61]:
fibo(2)

1

In [62]:
fibo(6)

8